### ISSUE TITLE
Shell doesn't work

### ISSUE THREAD

**Issue by jesrig** [alebcay/openlens-node-pod-menu#16] opened 2023-02-03 16:27 UTC
I'm running Ubuntu 20.04 and I just installed Open Lens. When I had the regular Lens installed, I was able to use the shell icon to exec into my pod container. Now, even though I installed the @alebcay/openlens-node-pod-menu extension, while I do see the shell icon dropdown as before, nothing happens when I click the icon.

**Comment by alebcay** [comment] 2023-02-03 16:38
Hello, what version of OpenLens are you using? If it's a 6.4.0-beta.* version older than 6.4.0-beta.13, you may be affected by https://github.com/lensapp/lens/issues/7076.

This is caused by an issue with the Lens Extension API, which is in the OpenLens application itself (not in this plugin). It appears to be fixed as of 6.4.0-beta.13.

Note that there are some other functional issues with using this plugin with 6.4.0-beta.* versions of OpenLens, such as #15. The Lens team still seems to be patching up a bunch of loose ends and bug hunting after they refactored the code base recently.

**Comment by jesrig** [comment] 2023-02-03 17:01
Well, I"m a bit confused now. I'm was running version 6.4.0-beta.12, and when I saw you comment (and that .13 was just added today), I uninstalled .12 and installed .13. I am still getting the same issue.

The confusing part is, when I go to File -> Help -> About Open Lens, it still says the version is .12. But when I run `dpkg -l | grep lens`, it says I'm running version .13

**Comment by alebcay** [comment] 2023-02-03 19:20
I have seen this on a few occasions. Can you check if either of the folders `$XDG_CONFIG_HOME/OpenLens` or `~/.config/OpenLens` exists? If either exists, please delete it and try re-running OpenLens. Note that any application preferences, such as color scheme and editor/terminal font, may be lost.

After this, the About OpenLens dialog should show the updated version number.

**Comment by justdan96** [comment] 2023-02-06 11:34
Issue seems resolved in OpenLens 6.4.0-beta.13.

**Comment by jesrig** [comment] 2023-02-06 16:44
@alebcay I was able to remove `~/.config/OpenLens` and now the correct version of `6.4.0-beta.13` displays.

However, now not only can I not ssh into a container from OpenLens, I now no longer even see the icon to do so (as I did previously).

**Comment by alebcay** [comment] 2023-02-07 13:59
Can you check the list of installed extensions? You may need to install this extension again. If it's listed as installed, try uninstalling and reinstalling it.

**Comment by jesrig** [comment] 2023-02-07 14:11
@alebcay That worked! Thanks!

**Comment by alebcay** [comment] 2023-02-10 20:26
This should be fixed as of OpenLens `6.4.0-beta.13` now.

**Closed by alebcay** 2023-02-10 20:26 UTC
