### ISSUE TITLE
App crash at /pods

### ISSUE THREAD

**Issue by jesrig** [alebcay/openlens-node-pod-menu#17] opened 2023-02-03 17:03 UTC
I'm running Open Lense 6.4.0-beta.12 (or maybe .13?... see here https://github.com/alebcay/openlens-node-pod-menu/issues/16#issuecomment-1416148534)

I get the following error when I click on the node link on my pod:

Component stack:

    at NodeMenu (/home/joseph/.k8slens/extensions/alebcay--openlens-node-pod-menu/dist/renderer.js:205:21)
    at MenuItem
    at ul
    at NonInjectedMenu (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:804038:9)
    at NonInjectedMenuActions (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:803879:9)
    at NonInjectedKubeObjectMenu (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:800684:9)
    at div
    at div
    at div
    at NonInjectedAnimate (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:769531:13)
    at NonInjectedDrawer (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:788947:9)
    at observerComponent (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:609629:16)
    at ObserverComponent (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:609677:23)
    at NonInjectedErrorBoundary (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:789420:9)
    at observerComponent (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:609629:16)
    at ThemeProvider (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:496936:24)
    at Router (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:651759:30)

and 

Error stack:

Error: Tried to get DI container using legacy globals where there is no containers available.
    at legacy_global_di_for_extension_api_getLegacyGlobalDiForExtensionApi (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:376892:15)
    at Object.get (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:378981:26)
    at Object.getKubectlPath (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:380019:41)
    at NodeMenu (/home/joseph/.k8slens/extensions/alebcay--openlens-node-pod-menu/dist/renderer.js:210:41)
    at Ch (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:650277:137)
    at ck (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:650387:460)
    at bk (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:650370:347)
    at ak (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:650370:278)
    at Tj (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:650370:138)
    at Lj (https://c498e8dc3b07e4719467083e26d95ba7.lens.app:46653/build/lens.js?ac50173bdba94d0f1e03:650363:163)

**Comment by alebcay** [comment] 2023-02-10 20:27
Are you still able to reproduce this issue in OpenLens `6.4.0-beta.13`? I think this may be the same root cause as #16, in which case it should hopefully be fixed now.

**Comment by jesrig** [comment] 2023-02-12 02:56
Nope, all good now, thanks!

**Closed** 2023-02-12 13:22 UTC
